/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.1.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

dependencies {
    testImplementation("junit:junit:4.13")
    testCompile("org.mockito:mockito-core:3.3.3")

    implementation("org.eclipse.jetty:jetty-server:9.4.27.v20200227")
    implementation("org.springframework:spring-context:5.2.5.RELEASE")

}

application {
    // Define the main class for the application.
    mainClassName = "io.ideas.engineering.ioc.IoC"
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "${application.mainClassName}"
    }

    from(sourceSets.main.get().output)
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get()
                .filter { it.name.endsWith("jar") }
                .map { zipTree(it) }
    })
}
